image: node:18.18.0

stages:
  - build

build_job:
  stage: build
  script:
    - echo "安装 pnpm..."
    - npm install -g pnpm

    - echo "清理旧依赖..."
    - rm -rf node_modules

    - echo "安装项目依赖..."
    - pnpm config set ignore-scripts true
    - pnpm install --legacy-peer-deps

    - echo "开始构建项目..."
    - pnpm run build

  only:
    - master