version: 1.0

stages:
  - build

build_job:
  stage: build
  script:
    # Step 1: 安装 nvm
    - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
    - export NVM_DIR="$HOME/.nvm"
    - [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

    # Step 2: 安装并使用 Node.js 18
    - nvm install 18
    - echo "当前Node版本：$(node -v)"
    - echo "当前NPM版本：$(npm -v)"

    # Step 3: 安装依赖
    - npm ci  # 或者使用 npm install --legacy-peer-deps 如果有兼容问题

    # Step 4: 构建项目
    - npm run build

  only:
    - master