version: 1.0

stages:
  - build

build_job:
  stage: build
  script:
    - set -x  # 启用调试模式1
    - echo "开始安装 nvm..."
    - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
    - echo "加载 nvm..."
    - export NVM_DIR="$HOME/.nvm"
    - source "$NVM_DIR/nvm.sh"
    - echo "安装 Node.js 18..."
    - nvm install 18
    - echo "切换到 Node.js 18..."
    - nvm use 18
    - echo "当前 Node.js 版本: $(node -v)"
    - echo "当前 npm 版本: $(npm -v)"
    - echo "清理旧依赖..."
    - rm -rf node_modules package-lock.json
    - echo "安装项目依赖..."
    - npm config set ignore-scripts true
    - npm install --legacy-peer-deps
    - echo "构建项目..."
    - npm run build
  only:
    - master