version: 1.0
image: node:18

stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - echo "开始构建..."
    - npm install # 或者使用其他包管理工具如yarn
    - npm run build
  only:
    - master # 仅当push到master分支时触发

test_job:
  stage: test
  script:
    - echo "运行测试..."
    - npm test # 执行单元测试或其他类型的测试
  only:
    - master # 仅当push到master分支时触发

deploy_job:
  stage: deploy
  script:
    - echo "开始部署..."
    - bash ./deploy.sh # 根据需要编写部署脚本
  only:
    - master # 仅当push到master分支时触发